### ISSUE TITLE
Physics calendar is broken

### ISSUE THREAD

**Issue by strugee** [itmeson/markbetnel.com#1]
http://markbetnel.com/courses/physics/fall2015/calendar.html sits at "loading" forever. I've seen this on `calendar.saasrobotics.com` too; seems like Google broke iframe embeds.

**Comment by itmeson** [comment]
Why aren't you working on SAT practice?

:)

--Mark

**Comment by itmeson** [comment]
It's working for me right now.  What browser?

**Comment by strugee** [comment]
@itmeson I'm on Firefox Nightly, built 9/22. Let me make sure I don't have any extensions interfering, as well.

**Comment by strugee** [comment]
Yeah, it's on my end. Sorry for the noise.
